services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    volumes:
      - ./pb_data:/pb_data
      - ./pb_public:/pb_public
      - ./pb_migrations:/pb_migrations
    ports:
      - "8090:8090" # solo accesible dentro de tu red local, no expuesto a internet
    restart: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
      - DUCKDNS_API_TOKEN=${DUCKDNS_API_TOKEN}
    depends_on:
      - pocketbase
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - TZ=Europe/Madrid
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_API_TOKEN}
      - LOG_FILE=false
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
